var tableElements = [{
        name: "Группы элементов",
        span: "span-11",
        type: "title",
        color: "beige",
    },
    {
        name: "I",
        type: "title",
        color: "beige",
    },
    {
        name: "II",
        type: "title",
        color: "beige",
    },
    {
        name: "III",
        type: "title",
        color: "beige",
    },
    {
        name: "IV",
        type: "title",
        color: "beige",
    },
    {
        name: "V",
        type: "title",
        color: "beige",
    },
    {
        name: "VI",
        type: "title",
        color: "beige",
    },
    {
        name: "VII",
        type: "title",
        color: "beige",
    },
    {
        name: "VIII",
        type: "title",
        color: "beige",
        span: "span-4",
    },
    {
        symbol: "H",
        index: "1",
        mass: "1,008",
        name: "Водород",
        electrons: [1],
        side: "left",
        color: "purple",
        type: "element",
    },
    { type: "empty" },
    { type: "empty" },
    { type: "empty" },
    { type: "empty" },
    { type: "empty" },
    { type: "empty" },
    { type: "empty" },
    { type: "empty" },
    { type: "empty" },
    {
        symbol: "He",
        index: "2",
        mass: "4,0026",
        name: "Гелий",
        electrons: [2],
        side: "left",
        color: "purple",
        type: "element",
    },
    {
        symbol: "Li",
        index: "3",
        mass: "6,94",
        name: "Литий",
        electrons: [2, 1],
        side: "left",
        color: "purple",
        type: "element",
    },
    {
        symbol: "Be",
        index: "4",
        mass: "9,0122",
        name: "Бериллий",
        electrons: [2, 2],
        side: "left",
        color: "purple",
        type: "element",
    },
    {
        symbol: "B",
        index: "5",
        mass: "10,81",
        name: "Бор",
        electrons: [2, 3],
        side: "left",
        color: "yellow",
        type: "element",
    },
    {
        symbol: "C",
        index: "6",
        mass: "12,011",
        name: "Углерод",
        electrons: [2, 4],
        side: "left",
        color: "yellow",
        type: "element",
    },
    {
        symbol: "N",
        index: "7",
        mass: "14,007",
        name: "Азот",
        electrons: [2, 5],
        side: "left",
        color: "yellow",
        type: "element",
    },
    {
        symbol: "O",
        index: "8",
        mass: "15,999",
        name: "Кислород",
        electrons: [2, 6],
        side: "left",
        color: "yellow",
        type: "element",
    },
    {
        symbol: "F",
        index: "9",
        mass: "18,998",
        name: "Фтор",
        electrons: [2, 7],
        side: "left",
        color: "yellow",
        type: "element",
    },
    { type: "empty" },
    { type: "empty" },
    { type: "empty" },
    {
        symbol: "Ne",
        index: "10",
        mass: "20,180",
        name: "Неон",
        electrons: [2, 8],
        side: "left",
        color: "yellow",
        type: "element",
    },
    {
        symbol: "Na",
        index: "11",
        mass: "22,990",
        name: "Натрий",
        electrons: [2, 8, 1],
        side: "left",
        color: "purple",
        type: "element",
    },
    {
        symbol: "Mg",
        index: "12",
        mass: "24,305",
        name: "Магний",
        electrons: [2, 8, 2],
        side: "left",
        color: "purple",
        type: "element",
    },
    {
        symbol: "Al",
        index: "13",
        mass: "26,982",
        name: "Алюминий",
        electrons: [2, 8, 3],
        side: "left",
        color: "yellow",
        type: "element",
    },
    {
        symbol: "Si",
        index: "14",
        mass: "28,085",
        name: "Кремний",
        electrons: [2, 8, 4],
        side: "left",
        color: "yellow",
        type: "element",
    },
    {
        symbol: "P",
        index: "15",
        mass: "30,974",
        name: "Фосфор",
        electrons: [2, 8, 5],
        side: "left",
        color: "yellow",
        type: "element",
    },
    {
        symbol: "S",
        index: "16",
        mass: "32,06",
        name: "Сера",
        electrons: [2, 8, 6],
        side: "left",
        color: "yellow",
        type: "element",
    },
    {
        symbol: "Cl",
        index: "17",
        mass: "Хлор",
        name: "35,45",
        electrons: [2, 8, 7],
        side: "left",
        color: "yellow",
        type: "element",
    },
    { type: "empty" },
    { type: "empty" },
    { type: "empty" },
    {
        symbol: "Ar",
        index: "18",
        mass: "39,948",
        name: "Аргон",
        electrons: [2, 8, 8],
        side: "left",
        color: "yellow",
        type: "element",
    },
    {
        symbol: "K",
        index: "19",
        mass: "39,098",
        name: "Калий",
        electrons: [2, 8, 8, 1],
        side: "left",
        color: "purple",
        type: "element",
    },
    {
        symbol: "Ca",
        index: "20",
        mass: "40,078",
        name: "Кальций",
        electrons: [2, 8, 8, 2],
        side: "left",
        color: "purple",
        type: "element",
    },
    {
        symbol: "Sc",
        index: "21",
        mass: "44,956",
        name: "Скандий",
        electrons: [2, 8, 9, 2],
        side: "right",
        color: "blue",
        type: "element",
    },
    {
        symbol: "Ti",
        index: "22",
        mass: "47,867",
        name: "Титан",
        electrons: [2, 8, 9, 2],
        side: "right",
        color: "blue",
        type: "element",
    },
    {
        symbol: "V",
        index: "23",
        mass: "50,942",
        name: "Ванадий",
        electrons: [2, 8, 10, 2],
        side: "right",
        color: "blue",
        type: "element",
    },
    {
        symbol: "Cr",
        index: "24",
        mass: "51,996",
        name: "Хром",
        electrons: [2, 8, 11, 2],
        side: "right",
        color: "blue",
        type: "element",
    },
    {
        symbol: "Mn",
        index: "25",
        mass: "54,938",
        name: "Марганец",
        electrons: [2, 8, 12, 2],
        side: "right",
        color: "blue",
        type: "element",
    },
    {
        symbol: "Fe",
        index: "26",
        mass: "55,845",
        name: "Железо",
        electrons: [2, 8, 13, 2],
        side: "right",
        color: "blue",
        type: "element",
    },
    {
        symbol: "Co",
        index: "27",
        mass: "58,933",
        name: "Кобальт",
        electrons: [2, 8, 14, 2],
        side: "right",
        color: "blue",
        type: "element",
    },
    {
        symbol: "Ni",
        index: "28",
        mass: "58,693",
        name: "Никель",
        electrons: [2, 8, 15, 2],
        side: "right",
        color: "blue",
        type: "element",
    },
    { type: "empty" },
    {
        symbol: "Cu",
        index: "29",
        mass: "63,546",
        name: "Медь",
        electrons: [2, 8, 16, 2],
        side: "right",
        color: "blue",
        type: "element",
    },
    {
        symbol: "Zn",
        index: "30",
        mass: "65,38",
        name: "Цинк",
        electrons: [2, 8, 18, 1],
        side: "right",
        color: "blue",
        type: "element",
    },
    {
        symbol: "Ga",
        index: "31",
        mass: "69,723",
        name: "Галлий",
        electrons: [2, 8, 18, 2],
        side: "left",
        color: "yellow",
        type: "element",
    },
    {
        symbol: "Ge",
        index: "32",
        mass: "72,630",
        name: "Германий",
        electrons: [2, 8, 18, 3],
        side: "left",
        color: "yellow",
        type: "element",
    },
    {
        symbol: "As",
        index: "33",
        mass: "74,922",
        name: "Мышьяк",
        electrons: [2, 8, 18, 4],
        side: "left",
        color: "yellow",
        type: "element",
    },
    {
        symbol: "Se",
        index: "34",
        mass: "78,971",
        name: "Селен",
        electrons: [2, 8, 18, 5],
        side: "left",
        color: "yellow",
        type: "element",
    },
    {
        symbol: "Br",
        index: "35",
        mass: "79,904",
        name: "Бром",
        electrons: [2, 8, 18, 6],
        side: "left",
        color: "yellow",
        type: "element",
    },
    { type: "empty" },
    { type: "empty" },
    { type: "empty" },
    {
        symbol: "Kr",
        index: "36",
        mass: "83,798",
        name: "Криптон",
        electrons: [2, 8, 18, 7],
        side: "left",
        color: "yellow",
        type: "element",
    },
    {
        symbol: "rb",
        index: "37",
        mass: "85,468",
        name: "Рубидий",
        electrons: [2, 8, 18, 8, 1],
        side: "left",
        color: "purple",
        type: "element",
    },
    {
        symbol: "Sr",
        index: "38",
        mass: "87,62",
        name: "Стронций",
        electrons: [2, 8, 18, 8, 2],
        side: "left",
        color: "purple",
        type: "element",
    },
    {
        symbol: "Y",
        index: "39",
        mass: "88,906",
        name: "Иттрий",
        electrons: [2, 8, 18, 9, 2],
        side: "right",
        color: "blue",
        type: "element",
    },
    {
        symbol: "Zr",
        index: "40",
        mass: "91,224",
        name: "Цирконий",
        electrons: [2, 8, 8, 10, 2],
        side: "right",
        color: "blue",
        type: "element",
    },
    {
        symbol: "Nd",
        index: "41",
        mass: "92,906",
        name: "Ниобий",
        electrons: [2, 8, 8, 12, 1],
        side: "right",
        color: "blue",
        type: "element",
    },
    {
        symbol: "Mo",
        index: "42",
        mass: "95,95",
        name: "Молибден",
        electrons: [2, 8, 8, 13, 1],
        side: "right",
        color: "blue",
        type: "element",
    },
    {
        symbol: "Tc",
        index: "43",
        mass: "98",
        name: "Технеций",
        electrons: [2, 8, 8, 13, 2],
        side: "right",
        color: "blue",
        type: "element",
    },
    {
        symbol: "Ru",
        index: "44",
        mass: "101,07",
        name: "Рутений",
        electrons: [2, 8, 18, 15, 1],
        side: "right",
        color: "blue",
        type: "element",
    },
    {
        symbol: "Rh",
        index: "45",
        mass: "102,91",
        name: "Родий",
        electrons: [2, 8, 18, 16, 1],
        side: "right",
        color: "blue",
        type: "element",
    },
    {
        symbol: "Pd",
        index: "46",
        mass: "106,42",
        name: "Палладий",
        electrons: [2, 8, 18, 18],
        side: "right",
        color: "blue",
        type: "element",
    },
    { type: "empty" },
    {
        symbol: "Ag",
        index: "47",
        mass: "107,87",
        name: "Серебро",
        electrons: [2, 8, 18, 18, 1],
        side: "right",
        color: "blue",
        type: "element",
    },
    {
        symbol: "Cd",
        index: "48",
        mass: "112,41",
        name: "Кадмий",
        electrons: [2, 8, 18, 18, 2],
        side: "right",
        color: "blue",
        type: "element",
    },
    {
        symbol: "Ln",
        index: "49",
        mass: "114,82",
        name: "Индий",
        electrons: [2, 8, 18, 18, 3],
        side: "left",
        color: "yellow",
        type: "element",
    },
    {
        symbol: "Sn",
        index: "50",
        mass: "118,71",
        name: "Олово",
        electrons: [2, 8, 18, 18, 4],
        side: "left",
        color: "yellow",
        type: "element",
    },
    {
        symbol: "Sb",
        index: "51",
        mass: "121,76",
        name: "Сурьма",
        electrons: [2, 8, 18, 18, 5],
        side: "left",
        color: "yellow",
        type: "element",
    },
    {
        symbol: "Te",
        index: "52",
        mass: "127,60",
        name: "Теллур",
        electrons: [2, 8, 18, 18, 6],
        side: "left",
        color: "yellow",
        type: "element",
    },
    {
        symbol: "L",
        index: "53",
        mass: "126,90",
        name: "Иод",
        electrons: [2, 8, 18, 18, 7],
        side: "left",
        color: "yellow",
        type: "element",
    },
    { type: "empty" },
    { type: "empty" },
    { type: "empty" },
    {
        symbol: "Xe",
        index: "54",
        mass: "131,29",
        name: "Ксенон",
        electrons: [2, 8, 18, 18, 8],
        side: "left",
        color: "yellow",
        type: "element",
    },
    {
        symbol: "Cs",
        index: "55",
        mass: "132,91",
        name: "Цезий",
        electrons: [2, 8, 18, 18, 8, 1],
        side: "left",
        color: "purple",
        type: "element",
    },
    {
        symbol: "Ba",
        index: "56",
        mass: "137,33",
        name: "Барий",
        electrons: [2, 8, 18, 18, 8, 2],
        side: "left",
        color: "purple",
        type: "element",
    },
    { type: "lan", index: "57-71", name: "Лантаноиды", color: "green" },
    {
        symbol: "La",
        index: "57",
        mass: "138,91",
        name: "Лантан",
        electrons: [2, 8, 18, 18, 9, 2],
        side: "right",
        color: "green",
        type: "lantanoid",
    },
    {
        symbol: "Ce",
        index: "58",
        mass: "140,12",
        name: "Церий",
        electrons: [2, 8, 18, 19, 9, 2],
        side: "right",
        color: "green",
        type: "lantanoid",
    },
    {
        symbol: "Pr",
        index: "59",
        mass: "140,91",
        name: "Празеодим",
        electrons: [2, 8, 18, 18, 9, 2],
        side: "right",
        color: "green",
        type: "lantanoid",
    },
    {
        symbol: "Nd",
        index: "60",
        mass: "144,24",
        name: "Неодим",
        electrons: [2, 8, 18, 21, 8, 2],
        side: "right",
        color: "green",
        type: "lantanoid",
    },
    {
        symbol: "Pm",
        index: "61",
        mass: "145",
        name: "Прометий",
        electrons: [2, 8, 18, 22, 8, 2],
        side: "right",
        color: "green",
        type: "lantanoid",
    },
    {
        symbol: "Sm",
        index: "62",
        mass: "150,36",
        name: "Самарий",
        electrons: [2, 8, 18, 23, 8, 2],
        side: "right",
        color: "green",
        type: "lantanoid",
    },
    {
        symbol: "Eu",
        index: "63",
        mass: "151,96",
        name: "Европий",
        electrons: [2, 8, 18, 25, 8, 2],
        side: "right",
        color: "green",
        type: "lantanoid",
    },
    {
        symbol: "Gd",
        index: "64",
        mass: "157,25",
        name: "Гадолиний",
        electrons: [2, 8, 18, 25, 9, 2],
        side: "right",
        color: "green",
        type: "lantanoid",
    },
    {
        symbol: "Tb",
        index: "65",
        mass: "158,93",
        name: "Тербий",
        electrons: [2, 8, 18, 27, 8, 2],
        side: "right",
        color: "green",
        type: "lantanoid",
    },
    {
        symbol: "Dy",
        index: "66",
        mass: "162,50",
        name: "Диспрозий",
        electrons: [2, 8, 18, 28, 8, 2],
        side: "right",
        color: "green",
        type: "lantanoid",
    },
    {
        symbol: "Ho",
        index: "67",
        mass: "164,93",
        name: "Гольмий",
        electrons: [2, 8, 18, 29, 8, 2],
        side: "right",
        color: "green",
        type: "lantanoid",
    },
    {
        symbol: "Er",
        index: "68",
        mass: "167,26",
        name: "Эрбий",
        electrons: [2, 8, 18, 30, 8, 2],
        side: "right",
        color: "green",
        type: "lantanoid",
    },
    {
        symbol: "Tm",
        index: "69",
        mass: "168,93",
        name: "Тулий",
        electrons: [2, 8, 18, 31, 8, 2],
        side: "right",
        color: "green",
        type: "lantanoid",
    },
    {
        symbol: "Yb",
        index: "70",
        mass: "173,05",
        name: "Иттербий",
        electrons: [2, 8, 18, 32, 8, 2],
        side: "right",
        color: "green",
        type: "lantanoid",
    },
    {
        symbol: "lu",
        index: "71",
        mass: "174,97",
        name: "Лютеций",
        electrons: [2, 8, 18, 32, 9, 2],
        side: "right",
        color: "green",
        type: "lantanoid",
    },
    {
        symbol: "Hf",
        index: "72",
        mass: "178,49",
        name: "Гафний",
        electrons: [2, 8, 18, 32, 10, 2],
        side: "right",
        color: "blue",
        type: "element",
    },
    {
        symbol: "Ta",
        index: "73",
        mass: "180,95",
        name: "Тантал",
        electrons: [2, 8, 18, 32, 11, 2],
        side: "right",
        color: "blue",
        type: "element",
    },
    {
        symbol: "W",
        index: "74",
        mass: "183,84",
        name: "Вольфрам",
        electrons: [2, 8, 18, 32, 12, 2],
        side: "right",
        color: "blue",
        type: "element",
    },
    {
        symbol: "Re",
        index: "75",
        mass: "186,21",
        name: "Рений",
        electrons: [2, 8, 18, 32, 13, 2],
        side: "right",
        color: "blue",
        type: "element",
    },
    {
        symbol: "Os",
        index: "76",
        mass: "190,23",
        name: "Осмий",
        electrons: [2, 8, 18, 32, 14, 2],
        side: "right",
        color: "blue",
        type: "element",
    },
    {
        symbol: "Lr",
        index: "77",
        mass: "192,22",
        name: "Иридий",
        electrons: [2, 8, 18, 32, 15, 2],
        side: "right",
        color: "blue",
        type: "element",
    },
    {
        symbol: "Pt",
        index: "78",
        mass: "195,08",
        name: "Платина",
        electrons: [2, 8, 18, 32, 17, 1],
        side: "right",
        color: "blue",
        type: "element",
    },
    { type: "empty" },
    {
        symbol: "Au",
        index: "79",
        mass: "196,97",
        name: "Золото",
        electrons: [2, 8, 18, 32, 18, 1],
        side: "right",
        color: "blue",
        type: "element",
    },
    {
        symbol: "Hg",
        index: "80",
        mass: "200,59",
        name: "Ртуть",
        electrons: [2, 8, 18, 32, 18, 2],
        side: "right",
        color: "blue",
        type: "element",
    },
    {
        symbol: "Tl",
        index: "81",
        mass: "204,38",
        name: "Таллий",
        electrons: [2, 8, 18, 32, 18, 3],
        side: "left",
        color: "yellow",
        type: "element",
    },
    {
        symbol: "Pb",
        index: "82",
        mass: "207,2",
        name: "Свинец",
        electrons: [2, 8, 18, 32, 18, 4],
        side: "left",
        color: "yellow",
        type: "element",
    },
    {
        symbol: "Bi",
        index: "83",
        mass: "208,98",
        name: "Висмут",
        electrons: [2, 8, 18, 32, 18, 5],
        side: "left",
        color: "yellow",
        type: "element",
    },
    {
        symbol: "Po",
        index: "84",
        mass: "209",
        name: "Полоний",
        electrons: [2, 8, 18, 32, 18, 6],
        side: "left",
        color: "yellow",
        type: "element",
    },
    {
        symbol: "At",
        index: "85",
        mass: "210",
        name: "Астат",
        electrons: [2, 8, 18, 32, 18, 7],
        side: "left",
        color: "yellow",
        type: "element",
    },
    { type: "empty" },
    { type: "empty" },
    { type: "empty" },
    {
        symbol: "Rn",
        index: "86",
        mass: "222",
        name: "Радон",
        electrons: [2, 8, 18, 32, 18, 8],
        side: "left",
        color: "yellow",
        type: "element",
    },
    {
        symbol: "Fr",
        index: "87",
        mass: "223",
        name: "Франций",
        electrons: [2, 8, 18, 32, 18, 8, 1],
        side: "left",
        color: "purple",
        type: "element",
    },
    {
        symbol: "Ra",
        index: "88",
        mass: "226",
        name: "Радий",
        electrons: [2, 8, 18, 32, 18, 8, 2],
        side: "left",
        color: "purple",
        type: "element",
    },
    { type: "act", index: "89-103", name: "Актиноиды", color: "green" },
    {
        symbol: "Ac",
        index: "89",
        mass: "227",
        name: "Актиний",
        electrons: [2, 8, 18, 32, 18, 9, 2],
        side: "right",
        color: "green",
        type: "actinoid",
    },
    {
        symbol: "Th",
        index: "90",
        mass: "232,04",
        name: "Торий",
        electrons: [2, 8, 18, 32, 18, 10, 2],
        side: "right",
        color: "green",
        type: "actinoid",
    },
    {
        symbol: "Pa",
        index: "91",
        mass: "231,04",
        name: "Протактиний",
        electrons: [2, 8, 18, 32, 20, 9, 2],
        side: "right",
        color: "green",
        type: "actinoid",
    },
    {
        symbol: "U",
        index: "92",
        mass: "238,03",
        name: "Уран",
        electrons: [2, 8, 18, 32, 21, 9, 2],
        side: "right",
        color: "green",
        type: "actinoid",
    },
    {
        symbol: "Np",
        index: "93",
        mass: "237",
        name: "Нептуний",
        electrons: [2, 8, 18, 32, 22, 9, 2],
        side: "right",
        color: "green",
        type: "actinoid",
    },
    {
        symbol: "Pu",
        index: "94",
        mass: "244",
        name: "Плутоний",
        electrons: [2, 8, 18, 32, 24, 8, 2],
        side: "right",
        color: "green",
        type: "actinoid",
    },
    {
        symbol: "Am",
        index: "95",
        mass: "243",
        name: "Америций",
        electrons: [2, 8, 18, 32, 25, 8, 2],
        side: "right",
        color: "green",
        type: "actinoid",
    },
    {
        symbol: "Cm",
        index: "96",
        mass: "247",
        name: "Кюрий",
        electrons: [2, 8, 18, 32, 25, 9, 2],
        side: "right",
        color: "green",
        type: "actinoid",
    },
    {
        symbol: "Bk",
        index: "97",
        mass: "247",
        name: "Берклий",
        electrons: [2, 8, 18, 32, 27, 8, 2],
        side: "right",
        color: "green",
        type: "actinoid",
    },
    {
        symbol: "Cf",
        index: "98",
        mass: "251",
        name: "Калифорний",
        electrons: [2, 8, 18, 32, 28, 8, 2],
        side: "right",
        color: "green",
        type: "actinoid",
    },
    {
        symbol: "Es",
        index: "99",
        mass: "252",
        name: "Эйнштейний",
        electrons: [2, 8, 18, 32, 29, 8, 2],
        side: "right",
        color: "green",
        type: "actinoid",
    },
    {
        symbol: "Fm",
        index: "100",
        mass: "257",
        name: "Фермий",
        electrons: [2, 8, 18, 32, 30, 8, 2],
        side: "right",
        color: "green",
        type: "actinoid",
    },
    {
        symbol: "Md",
        index: "101",
        mass: "258",
        name: "Менделевий",
        electrons: [2, 8, 18, 32, 31, 8, 2],
        side: "right",
        color: "green",
        type: "actinoid",
    },
    {
        symbol: "No",
        index: "102",
        mass: "259",
        name: "Нобелий",
        electrons: [2, 8, 18, 32, 32, 8, 2],
        side: "right",
        color: "green",
        type: "actinoid",
    },
    {
        symbol: "Lr",
        index: "103",
        mass: "266",
        name: "Лоуренсий",
        electrons: [2, 8, 18, 32, 32, 8, 3],
        side: "right",
        color: "green",
        type: "actinoid",
    },
    {
        symbol: "Rf",
        index: "104",
        mass: "267",
        name: "Резерфордий",
        electrons: [2, 8, 18, 32, 32, 10, 2],
        side: "right",
        color: "blue",
        type: "element",
    },
    {
        symbol: "Db",
        index: "105",
        mass: "268",
        name: "Дубний",
        electrons: [2, 8, 18, 32, 32, 11, 2],
        side: "right",
        color: "blue",
        type: "element",
    },
    {
        symbol: "Sg",
        index: "106",
        mass: "269",
        name: "Сиборгий",
        electrons: [2, 8, 18, 32, 32, 12, 2],
        side: "right",
        color: "blue",
        type: "element",
    },
    {
        symbol: "Bh",
        index: "107",
        mass: "270",
        name: "Борий",
        electrons: [2, 8, 18, 32, 32, 13, 2],
        side: "right",
        color: "blue",
        type: "element",
    },
    {
        symbol: "Hs",
        index: "108",
        mass: "277",
        name: "Хассий",
        electrons: [2, 8, 18, 32, 32, 14, 2],
        side: "right",
        color: "blue",
        type: "element",
    },
    {
        symbol: "Mt",
        index: "109",
        mass: "278",
        name: "Мейтнерий",
        electrons: [2, 8, 18, 32, 32, 15, 2],
        side: "right",
        color: "blue",
        type: "element",
    },
    {
        symbol: "Ds",
        index: "110",
        mass: "281",
        name: "Дармштадтий",
        electrons: [2, 8, 18, 32, 32, 17, 1],
        side: "right",
        color: "blue",
        type: "element",
    },
    {
        symbol: "Rg",
        index: "111",
        mass: "282",
        name: "Рентгений",
        electrons: [2, 8, 18, 32, 32, 17, 2],
        side: "right",
        color: "blue",
        type: "element",
    },
    {
        symbol: "Cn",
        index: "112",
        mass: "285",
        name: "Коперниций",
        electrons: [2, 8, 18, 32, 32, 18, 2],
        side: "right",
        color: "blue",
        type: "element",
    },
    {
        symbol: "Nh",
        index: "113",
        mass: "286",
        name: "Нихоний",
        electrons: [2, 8, 18, 32, 32, 18, 3],
        side: "right",
        color: "blue",
        type: "element",
    },
    {
        symbol: "Fl",
        index: "114",
        mass: "289",
        name: "Флеровий",
        electrons: [2, 8, 18, 32, 32, 18, 4],
        side: "right",
        color: "blue",
        type: "element",
    },
    {
        symbol: "Mc",
        index: "115",
        mass: "Московий",
        name: "290",
        electrons: [2, 8, 18, 32, 32, 18, 5],
        side: "right",
        color: "blue",
        type: "element",
    },
    {
        symbol: "Lv",
        index: "116",
        mass: "293",
        name: "Ливерморий",
        electrons: [2, 8, 18, 32, 32, 18, 6],
        side: "right",
        color: "blue",
        type: "element",
    },
    {
        symbol: "Ts",
        index: "117",
        mass: "294",
        name: "Теннессин",
        electrons: [2, 8, 18, 32, 32, 18, 7],
        side: "right",
        color: "blue",
        type: "element",
    },
    {
        symbol: "Og",
        index: "118",
        mass: "294",
        name: "Оганесон",
        electrons: [2, 8, 18, 32, 32, 18, 8],
        side: "right",
        color: "blue",
        type: "element",
    },
];